# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20160608_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Category'),
            preserve_default=False,
        ),
    ]
